const CACHE='pixelquest-v3';
const [
  '/', 'index.html','game.html','credits.html','editor.html','settings.html',
  'manifest.webmanifest',
  'assets/style.css',
  'js/select.js','js/game.js','js/editor.js','js/settings.js',
  'assets/sprites/hero_blue.png','assets/sprites/hero_red.png','assets/sprites/hero_green.png',
  'assets/sprites/npc.png','assets/sprites/tile_grass.png','assets/sprites/tile_path.png',
  'assets/sprites/tile_water.png','assets/sprites/tile_bridge.png','assets/sprites/enemy.png','assets/sprites/coin.png',
  'maps/chapter1.json','maps/chapter2.json',
  'story/chapters/chapter1.json','story/chapters/chapter2.json'
,
  'andes/index.html',
  'andes/game.html',
  'andes/world.html',
  'andes/gallery.html',
  'andes/raft.html',
  'andes/achievements.html',
  'andes/js/game.js',
  'andes/js/world.js',
  'andes/js/gallery.js',
  'andes/js/raft.js',
  'andes/js/achievements.js',
  'andes/assets/sprites/condor.png',
  'andes/assets/sprites/fisher.png',
  'andes/assets/sprites/raft.png',
  'andes/assets/sprites/tile_snow.png',
  'andes/assets/sprites/tile_rock.png',
  'andes/assets/sprites/tile_river.png',
  'andes/assets/sprites/tile_forest.png',
  'andes/assets/sprites/tile_sand.png',
  'andes/assets/sprites/tile_board.png',
  'andes/assets/sprites/tile_sand_foam.png',
  'andes/assets/sprites/tile_wave.png',
  'andes/assets/sprites/boss_wave.png',
  'andes/assets/sprites/coin.png',
  'andes/assets/sprites/npc.png',
  'andes/assets/sprites/hero_blue.png',
  'andes/assets/sprites/hero_red.png',
  'andes/assets/sprites/hero_green.png',
  'andes/assets/sprites/badge_forest.png',
  'andes/assets/sprites/badge_raft.png',
  'andes/assets/sprites/badge_boss.png',
  'andes/assets/sprites/badge_collection.png',
  'andes/assets/sprites/badge_campaign.png',
  'andes/maps/andes1.json',
  'andes/maps/andes2.json',
  'andes/maps/andes3.json',
  'andes/maps/andes4.json',
  'andes/maps/andes5.json',
  'andes/story/chapters/andes1.json',
  'andes/story/chapters/andes2.json',
  'andes/story/chapters/andes3.json',
  'andes/story/chapters/andes4.json',
  'andes/story/chapters/andes5.json',
  'andes/data/collectibles.json'];
self.addEventListener('install',e=>{ e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS))); });
self.addEventListener('fetch',e=>{ e.respondWith(caches.match(e.request).then(r=> r || fetch(e.request))); });
